### ISSUE TITLE
chakra ui background is completely random

### ISSUE THREAD

**Issue by xMdb** [hychat-mc/website#1]
happens on both prod and dev. should be gray (gray.900) no settings seem to apply

**Comment by EvernoteMC** [comment]
It might have something to do with the theme.

Have you tried adding a temporary button to toggle the theme to see if that helps?

**Comment by xMdb** [comment]
> It might have something to do with the theme.
> 
> Have you tried adding a temporary button to toggle the theme to see if that helps?

@EvernoteMC i got rid of the theme provider as for website we arent going to have a dark mode switch, i just want the background to be gray permanently
